# 389. Find the Difference
# You are given two strings s and t.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Return the letter that was added to t.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        if len(s)> len(t):
            for i in s:
                if s.count(i)>t.count(i):
                    return(i)
                    break
        if len(t)>len(s):
            for i in t:
                if t.count(i)>s.count(i):
                    return(i)
                    break